import React from 'react';
import ListGroup from "react-bootstrap/ListGroup";
import Spinner from "react-bootstrap/Spinner";

import { api, extract_sensors } from "./prometheus";

class LiveView extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      error: null,
      isLoaded: false,
      sensors: []
    };
  }

  componentDidMount() {
    // set this component to fetch newest values every 15 seconds.
    this.update();
    this.timerID = setInterval(
        () => this.update(),
        15000
    );
  }

  componentWillUnmount() {
    // stop polling the database when the component is unmounted.
    clearInterval(this.timerID);
  }

  update() {
    // %22 = double quote symbol
    // this query currently gets all metrics from the
    // "sensors" job, where the `__name__` attribute
    // does not match regex `(python|scrape).*`, since
    // those are auto-generated by prometheus.
    fetch(api + "query={job=%22sensors%22,__name__!~%22(python|scrape).*%22}")
        .then(res => res.json())
        .then(
            (result) => {
              this.setState({
                isLoaded: true,
                error: false,
                sensors: extract_sensors(result),
              });
            },
            // Note: it's important to handle errors here
            // instead of a catch() block so that we don't swallow
            // exceptions from actual bugs in components.
            (error) => {
              this.setState({
                isLoaded: true,
                error
              });
            }
        )
  }

  render() {
    const { error, isLoaded, sensors } = this.state;
    if (error) {
      return (
          <div>
            <p>Error: {error.message}</p>
            <p>Is Prometheus running on <a href={"http://localhost:9090"}>http://localhost:9090</a>?</p>
          </div>
      );
    }
    else if (!isLoaded) {
      return (
          <Spinner animation="border" role="status">
            <span className="sr-only">Loading...</span>
          </Spinner>
      );
    }
    else {
      return (
          <ListGroup>
             {sensors.map(sensor => (
                 // TODO: items need 'key' prop added.
                 //       Currently unable to, since the
                 //       `state` metric has two entries.
                 <ListGroup.Item>
                   {sensor.name}: {sensor.value}
                 </ListGroup.Item>
             ))}
           </ListGroup>
      );
    }
  }
}

export default LiveView;
